# Generated by Django 3.0.3 on 2021-06-01 06:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillRecordMain',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('costs', models.DecimalField(decimal_places=2, default='0', max_digits=9, verbose_name='总金额')),
                ('nums', models.IntegerField(default=0, verbose_name='购买量')),
                ('bill_status', models.CharField(default='未支付', max_length=128, verbose_name='订单状态')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '订单主记录',
                'verbose_name_plural': '订单主记录',
            },
        ),
        migrations.CreateModel(
            name='GoodsRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, verbose_name='商品名称')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='单价')),
                ('oldprice', models.DecimalField(decimal_places=2, default=99, max_digits=9, verbose_name='优惠前单价')),
                ('nums', models.IntegerField(default=0, verbose_name='库存余量')),
                ('pic', models.ImageField(default='/defaultIocn/gooddefault.jpg', upload_to='goodsImage', verbose_name='图片')),
                ('description', models.TextField(default='', verbose_name='描述')),
                ('delete_flag', models.IntegerField(default=0, verbose_name='删除标识')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '商品记录',
                'verbose_name_plural': '商品记录',
            },
        ),
        migrations.CreateModel(
            name='ShoppingCar',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nums', models.IntegerField(default=0, verbose_name='购买量')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ShoppingApp.GoodsRecord', verbose_name='商品')),
            ],
            options={
                'verbose_name': '购物车',
                'verbose_name_plural': '购物车',
            },
        ),
        migrations.CreateModel(
            name='BillRecordSub',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nums', models.IntegerField(default=0, verbose_name='购买量')),
                ('costs', models.DecimalField(decimal_places=2, default='0', max_digits=9, verbose_name='金额')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ShoppingApp.GoodsRecord', verbose_name='商品')),
                ('main_rec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ShoppingApp.BillRecordMain', verbose_name='订单')),
            ],
            options={
                'verbose_name': '订单明细',
                'verbose_name_plural': '订单明细',
            },
        ),
    ]
