# Generated by Django 3.0.3 on 2021-06-02 00:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ShoppingApp', '0002_auto_20210601_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodsrecord',
            name='nums',
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('brand', models.CharField(blank=True, max_length=20, null=True, verbose_name='品牌')),
                ('model', models.CharField(blank=True, max_length=30, null=True, verbose_name='车系')),
                ('volume', models.FloatField(blank=True, null=True, verbose_name='排量')),
                ('gearbox', models.CharField(blank=True, max_length=20, null=True, verbose_name='变速箱')),
                ('oldprice', models.DecimalField(decimal_places=2, default=99, max_digits=9, verbose_name='优惠前单价')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='单价')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='年份')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='车龄')),
                ('mileage', models.FloatField(blank=True, null=True, verbose_name='公里数')),
                ('horsepower', models.IntegerField(blank=True, null=True, verbose_name='扭矩')),
                ('torque', models.IntegerField(blank=True, null=True, verbose_name='马力')),
                ('transfer_number', models.IntegerField(blank=True, null=True, verbose_name='转手次数')),
                ('fuel', models.FloatField(blank=True, null=True, verbose_name='汽油')),
                ('image', models.CharField(blank=True, max_length=200, null=True, verbose_name='图片')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '汽车',
                'verbose_name_plural': '汽车',
            },
        ),
    ]
